server:
  port: 9527


spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh               # 路由的ID，没有固定规则但要求唯一
          #uri: http://localhost:8001     # 匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/**        # 断言，路径相匹配的进行路由

        - id: payment_routh2              # 路由的ID，没有固定规则但要求唯一
          #uri: http://localhost:8001     # 匹配后提供服务的路由地址
          uri: lb://cloud-payment-service # 配置动态路由后，访问路径http://localhost:9527/payment/lb，会在8001和8002切换，实现负载均衡
          predicates:
            - Path=/payment/lb/**         # 断言，路径相匹配的进行路由
            - After=2021-04-14T15:03:19.241+08:00[Asia/Shanghai] #表示在该时间后，请求才有效
            #- Before=2021-04-14T15:03:19.241+08:00[Asia/Shanghai]
            #- Between=2021-04-14T15:03:19.241+08:00[Asia/Shanghai],2021-04-14T15:03:19.241+08:00[Asia/Shanghai]
            #- Cookie=user,ak #curl http://localhost:9527/payment/lb --cookie "user=ak"，cmd访问
            #- Header=X-Request-Id,\d+  #请求头须含有X-Request-Id属性并且值为正整数的正则表达式。curl http://localhost:9527/payment/lb -H "X-Request-Id:10"
            #- Host=**.baidu.com  #如www.baidu.com可以成功
            #- Method=GET
            #- Query=username,\d+  #要有参数名username并且值还要是整数才能路由 如http://localhost:9527/payment/lb?username=31


#        - id: path_route3
#          uri: http://news.baidu.com/mli
#          predicates:
#            - Path=/mli/**


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
