spring:
  redis:
    host: 192.168.138.130
    port: 6379
    password: 666888
  mail:
    # 配置 SMTP 服务器地址
    host: smtp.qq.com
    # 发送者邮箱
    from: 3557201370@qq.com
    username: 3557201370@qq.com
    # 配置密码，注意不是真正的密码，而是刚刚申请到的授权码
    password: crgrgkqlcoqbcice
    # 端口号465或587
    port: 587
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8
    # 配置SSL 加密工厂
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true

server:
  port: 8081


#
#   另外，springboot所有的配置类，都有一个自动配置类 RedisAutoConfiguration
#   自动配置类都会绑定一个properties配置文件 RedisProperties
#
